name: Deploy to Amazon ECR (tagged)

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Tag to push (e.g. latest, 1.0, 1.1)"
        required: true
        default: latest

env:
  ECR_REPOSITORY: hello-nginx
  IMAGE_TAG: ${{ github.event.inputs.image_tag }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG lab-01-ecr-push/app
          docker push $REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
